open-policy-agent/vscode-opa

package.json, rego/package.json, src/extension.ts
Hey @tsandall, I was setting out to build my own vscode extension for rego and OPA but then found this. Wanted to help shape up your effort and (hopefully?) publish this extension to the VS Code marketplace.
This PR has some stylistic changes, recommended changes to the extension categories (https://code.visualstudio.com/docs/extensionAPI/extension-manifest), and support for `opa check` for the current `rego` file in the editor
=> Support for "opa check" + minor style changes and improvements

package.json, src/extension.ts, src/install-opa.ts, src/opa.ts, src/util.ts
- Introduce new 'opa.path' configuration
- Refactor opa-related helpers into opa.ts
- Refactor display utilities into util.ts
- Consolidate to using a single output channel called "OPA"
- Introduce install-opa module which will prompt to install, fetch releases from GH, choose appropriate release and install it
- Tested on Linux (Ubuntu 18.04) and Mac OS X 10.12.6 with VS Code 1.23.1
- TODO: Test on windows pls?
=>  Extension should offer to install the "opa" executable when it's not found

README.md, package-lock.json, package.json, src/extension.ts, src/opa.ts
This adds two new config options:
* `opa.roots` - Which defines directories to load as bundles when
evaluating opa commands. This will default to the workspace root,
and supports using a variable `${workspaceFolder}` for that.
* `opa.bundleMode` - Which defaults to true and enables using the
`--bundle` option versus `--data` flag (what older versions of the
plugin would do). This is intended as a stop-gap solution for
projects that were successfully using the plugin and require that
behavior.
=> Add config for bundle root directories and bundleMode

README.md, src/opa.ts
`opa.roots` already supports the conventional `${workspaceFolder}` built-in variable. This PR adds another conventional and useful variable: `${fileDirname}` which is resolved with the directory of the file opened in the active window. This was also mentioned in https://github.com/open-policy-agent/vscode-opa/issues/27 where a user intuitively tried to use this but the extension didn't support it then.
for reference: https://code.visualstudio.com/docs/editor/variables-reference
=> support fileDirname variable in roots configuration

README.md, src/extension.ts
Thanks for making this extension! I am using it when the workspace dir is containing multiple sub directories which contains policies. Usually when evaluating a policy in a directory I need to test it with an input that works for it so I have some input examples in the root and I need to manually rename input.json back and forth. With this PR we can have a local input.json (in the same dir as the policy) that will override the root input.json if it exists (if not then it's same as before).
This intent is also captured in this issue: https://github.com/open-policy-agent/vscode-opa/issues/27.
related: https://github.com/open-policy-agent/vscode-opa/issues/28
=> search for input relative to the active window

src/opa.ts
Clumsily introduced by me in PR #58.
=> Fixing error thrown when opa.path setting not set

package.json
and updating repository link to point to repo owned by open-policy-agent.
=> Bumping version to 0.10.0

CHANGELOG.md, README.md, package.json, src/extension.ts, src/opa.ts
Can be toggled through opa.strictMode configuration flag.
Fixing: #63
=> Adding support for compiler strict-mode for OPA check command

package-lock.json, package.json
Previously this had been removed due to this: 
These changes surfaced when runing vsce publish
=> Add activationEvents back since

src/extension.ts
This PR changes the file extension of the output file from `json` to `jsonc` to prevent VS Code from marking the comment as an error.
---
resolves #97
=> Use .jsonc extension for output.json

README.md, package.json, src/opa.ts
This PR adds a new setting (`opa.env`) that allows you to set environment variables that will then be passed to the process that is running OPA.
---
resolves #50
=> Add configuration to set environment variables for opa subprocess

src/ls/activate.ts, src/ls/clients/regal.ts
When VS code starts, there is an issue where the configuration is 'changed' multiple times during start-up. This happened too quickly for the activatedRegal function to reliably test if regal was running already and caused many servers to be started.
This meant that sometimes messages would be duplicated since many servers would send the same message.
The minimum regal version has also been bumped, to contain fixes for non-workspaced vs code instances. (see https://github.com/StyraInc/regal/pull/580)
=> Address issue in Regal LS startups

README.md
I think this must have been a full link for display at https://marketplace.visualstudio.com/items?itemName=tsandall.opa - so I have left it like that.
=> docs: correct eval.gif link

README.md, src/opa.ts, src/util.ts
Additionally, add a `${workspacePath}` for commands that don't accept a full URI including the `file://` schema.
=> Allow `${workspaceFolder}` to be used in env var values

.eslintrc.yml, .github/dependabot.yml, .github/workflows/build.yaml, package-lock.json, package.json, src/extension.ts, src/github-installer.ts, src/ls/clients/regal.ts, src/ls/configure.ts, src/opa.ts
* Add dependabot config
* Enable more linters and fix some issues
* Only lint `src` directory
* Add a few more categories
=> Various fixes

src/extension.ts
Defer `vscode.window.activeTextEditor` check in `opa.test.workspace` command activation, as there might still be a workspace loaded.
Might still break on editing a single file, but I think that behavior is rather undefined given the name of the command explicitly states it's for testing a workspace.
Fixes #115
=> Fix edge case in `opa.test.workspace` activation

package-lock.json, package.json
This is required with the version of types that we have upgraded to. This version is (1.87.0) quite recent, Feb 2024.
I think our other option is to downgrade the @types/vscode package.
This is blocking our next release: https://github.com/open-policy-agent/vscode-opa/actions/runs/8552690488/job/23434325929
=> Update vscode engine

.github/workflows/release.yaml
We have had an issue where the release thinks the directory is dirty and can't continue. This is a second attempt where the package.json file must be updated first, then a tag pushed, then the release automation can run.
=> Release: Require manual updates to the package.json

src/ls/clients/regal.ts
Since all other output channels seem named like their project.
=> Use "Regal" instead of "regal-ls"

.vscode/launch.json, src/ls/clients/regal.ts
This is enabled when developing the extension. MessageStrategy is a handy place to hook into with logs and a debugger when inspecting the messages between the client and server.
I thought this was a sensible default.
=> Enable connection message logging in debug mode

src/extension.ts
Formatting rego files using the language server is marginally faster than shelling out to the local opa binary.
Since Regal can provide formatting functionality, this should be used if available. This change alters the extension to use the formatting functionality of the Regal if the user has chosen to enable Regal.
If they disable Regal, then the opa fmt formatter will return.
=> lsp: Prefer server for formatting

src/ls/clients/regal.ts
This addresses an issue where the output channel would be recreated many times as Regal was restarted.
before 
https://github.com/open-policy-agent/vscode-opa/assets/1774239/a872e2ce-dbad-444f-b7af-de056ca36015
after
https://github.com/open-policy-agent/vscode-opa/assets/1774239/8eef8652-7162-4668-889a-b737edda9bca
=> regal: when restarting regal, reuse output channel

README.md, src/extension.ts
We are trying to standardize Rego developer env functionality on the Regal LS implementation to be able to offer a standardized experience to all Rego developers, regardless of their preferred editor.
Fmt on save and goto definition are now available as part of the language server and so should be accessed via that route instead.
=> fmt/goto-defn: drop functionality in favor of LSP implementation

package.json, syntaxes/markdown-inject.json
Based on the example provided in https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example
Fixes #176
=> Support syntax highlighting in markdown code blocks

README.md, src/opa.ts
When installing the extension in VS Code and proceeding with the prompt to install the OPA CLI binary, I noticed that the `amd64` version was installed on my `arm64` macbook:
This PR fixes that and ensures that the binary selected from the assets matches the platform architecture of the machine.
=> Check for OS architecture when installing OPA CLI

README.md, package.json, src/ls/clients/regal.ts
Will work with Regal v0.25.0 once that is released.
=> Allow setting formatter via configuration

src/ls/clients/regal.ts
This makes the distinction with undefined clearer.
https://github.com/user-attachments/assets/7301aa9c-1583-49d8-a70f-8cfb25be45cd
=> Show eval string values in quotes

src/ls/clients/regal.ts
This updates the hover message for print decorations to also show the full print output.
Similar to large eval results, large outputs are not pre formatted.
https://github.com/user-attachments/assets/16c39d63-9646-45d1-b0da-d653e48f1f20
=> Show print output on hover

src/da/activate.ts, src/extension.ts
And enabling 'stopOnEntry' by default.
=> Inferring input.json location for debug workspace launcher

src/ls/clients/regal.ts
This may be called from an LSP server to have a debugging session started with the launch configuration in the payload.
=> Add startDebugging handler

.github/workflows/build.yaml, package-lock.json, package.json
This extends the compile check to confirm that vsce can actually build the package.
I am mostly adding this as a further check for dependabot PRs.
=> build: Confirm that ext pkg can be built

src/util.ts
replaceWorkspaceFolderPathVariable's previous implementation would use partially %-encoded paths in the replacement string. This would cause an issue on windows hosts where the files would not be readable at these incorrect paths.
=> util: fix bug in replaceWorkspaceFolderPathVariable
