open-policy-agent/vscode-opa

README.md, package-lock.json, package.json, src/extension.ts
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Add eval package and eval selection commands

package.json, src/install-opa.ts
Fixes: https://github.com/tsandall/vscode-opa/issues/15
I also got the cryptic error message when attempting to download and this change fixed it for me and should fix it for others as well without breaking anyone for whom it was working fine.
=> fix download asset

src/extension.ts
This depends on https://github.com/open-policy-agent/opa/pull/2408
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> Add support for go-to-definition in rego

README.md, src/extension.ts
Register OPA DocumentFormattingEditProvider for rego filetype using `opa fmt` CLI
Closes #36
=> Add OPA document editor formatter

package-lock.json, package.json, src/extension.ts, src/opa.ts, syntaxes/Rego.tmLanguage
This PR also includes a commit that bumps the version to v0.8.0 which should have been pushed a while ago!
=> Add support for in keyword and print function

package-lock.json, package.json
The vscode install script run during 'npm install' pulls down content from a stale URL; throwing an error.
=> Migrating from vscode dependency to @types/vscode

src/opa.ts
=> Resolve ${workspaceFolder} variable in opa.path setting

.gitignore, src/extension.ts, src/opa.ts
Also adding .DS_Store to .gitignore
=> Fixing linter warnings

src/extension.ts
=> Fixing issue where 'Check File Syntax' command produces no output

README.md, package.json, src/extension.ts, src/opa.ts
for passing --schema flag to eval- and check commands.
Fixes: #54
=> Adding opa.schema setting

CHANGELOG.md, README.md, src/extension.ts, src/opa.ts
=> Making it possible to run OPA commands on single file not in workspace

syntaxes/Rego.tmLanguage
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> enable syntax highlighting of the every keyword

CHANGELOG.md
Adding entry for 'every' keyword highlighting.
=> Updating changelog for 0.11

syntaxes/Rego.tmLanguage
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> Add if and contains keyword highlighting

README.md, src/opa.ts
Signed-off-by: Michael Sorens <birdwatcher42@gmail.com>
=> cosmetic readme updates

src/opa.ts
=> Strip protocol from ${workspaceFolder} when used in opa.path

src/opa.ts
This PR should fix the bug mentioned in #107.
@DrMagPie, can you please test if this fixes your error, since I could not reproduce the error you mentioned.
---
caused by #103
fixes #107
=> Fix for `OPA: Evaluate Package` fails on some systems

README.md
=> fix(docs): fix docs links

package-lock.json, package.json
Remove dependencies that we get transitively anyway, and avoid having dependabot complain about anything but the main dependency.
=> Dependencies cleanup

src/extension.ts, src/ls/clients/regal.ts
https://github.com/user-attachments/assets/902df2bc-d902-4e6d-b1ef-e8a26c25323f
=> Handle EvalResult message from Regal Language server

src/ls/clients/regal.ts
This makes it clear to the user that it's the whole document getting eval'ed and not the indididual definition
https://github.com/user-attachments/assets/736dd8f3-f0f8-416d-b29f-de564fde4d48
=> Display result next to each incremental definition

src/ls/clients/regal.ts
=> Print output

README.md
Also mentioned in the `input.json` section.
=> Add code lens evaluation to list of features

src/ls/clients/regal.ts
Regal now correctly sends back print output not just by **line** but as **file -> line**. The previous assumption that only lines from the current file would be returned was wrong of course, and could lead to print output from other files getting displayed in the editor.
Ideally we'd be able to decorate lines in any file where print output is provided, but for now, we'll just show it in the active editor window. In order to still be able to see print output from other files, we'll send the output of all to the Regal output channel.
=> Adapt to new `print` output map structure

src/ls/clients/regal.ts
Related to: https://github.com/StyraInc/regal/pull/1176
This PR allows the above to be merged, to better support feature flags of different clients in Regal's LSP.
=> lsp: Explicitly enable custom LSP features
